// Regression Test 2
// Checks whether multifiles compiled with -mlocal-offsets produces proper offsets.
//
// RUN: %gta3sc %s --config=gta3 -mlocal-offsets -emit-ir2 -o - | %FileCheck %s
//
LAUNCH_MISSION subscript.sc
LOAD_AND_LAUNCH_MISSION miss1.sc
main_label:
GOTO main_label
TERMINATE_THIS_SCRIPT

// CHECK-NEXT-L: LAUNCH_MISSION %MAIN_2
// CHECK-NEXT-L: LOAD_AND_LAUNCH_MISSION_INTERNAL 0i8
// CHECK-NEXT-L: MAIN_1:
// CHECK-NEXT-L: GOTO %MAIN_1
// CHECK-NEXT-L: TERMINATE_THIS_SCRIPT
// CHECK-NEXT-L: MAIN_2:
// CHECK-NEXT-L: SCRIPT_NAME 'SUBSC'
// CHECK-NEXT-L: MAIN_3:
// CHECK-NEXT-L: GOTO %MAIN_3
// CHECK-NEXT-L: TERMINATE_THIS_SCRIPT
// CHECK-NEXT-L: #MISSION_BLOCK_START 0
// CHECK-NEXT-L: SCRIPT_NAME 'MISS1'
// CHECK-NEXT-L: MISSION_0_1:
// CHECK-NEXT-L: GOTO %MISSION_0_1
// CHECK-NEXT-L: TERMINATE_THIS_SCRIPT
// CHECK-NEXT-L: #MISSION_BLOCK_END
