// Regression Test 4
// Ensures file includers when used from subscripts onwards uses labels.
//
// RUN: %gta3sc %s --config=gta3 -emit-ir2 -o - | %FileCheck %s
//
LAUNCH_MISSION subscript.sc
LOAD_AND_LAUNCH_MISSION miss1.sc
TERMINATE_THIS_SCRIPT

// CHECK-NEXT-L: LAUNCH_MISSION @MAIN_1
// CHECK-NEXT-L: LOAD_AND_LAUNCH_MISSION_INTERNAL 0i8
// CHECK-NEXT-L: TERMINATE_THIS_SCRIPT
// CHECK-NEXT-L: MAIN_1:
// CHECK-NEXT-L: SCRIPT_NAME 'SUBSC'
// CHECK-NEXT-L: GOSUB_FILE @MAIN_2 @MAIN_2
// CHECK-NEXT-L: LAUNCH_MISSION @MAIN_2
// CHECK-NEXT-L: TERMINATE_THIS_SCRIPT
// CHECK-NEXT-L: MAIN_2:
// CHECK-NEXT-L: GOTO @MAIN_2
// CHECK-NEXT-L: #MISSION_BLOCK_START 0
// CHECK-NEXT-L: SCRIPT_NAME 'MISS1'
// CHECK-NEXT-L: GOSUB_FILE %MISSION_0_1 %MISSION_0_1
// CHECK-NEXT-L: LAUNCH_MISSION %MISSION_0_1
// CHECK-NEXT-L: TERMINATE_THIS_SCRIPT
// CHECK-NEXT-L: MISSION_0_1:
// CHECK-NEXT-L: GOTO %MISSION_0_1
// CHECK-NEXT-L: #MISSION_BLOCK_END
