// RUN: %gta3sc %s --config=gta3 -emit-ir2 | %FileCheck %s

VAR_INT x

// CHECK-NEXT-L: ANDOR 0i8
// CHECK-NEXT-L: IS_THING_EQUAL_TO_THING &8 0i8
// CHECK-NEXT-L: GOTO_IF_FALSE @MAIN_1
IF x = 0
    // CHECK-NEXT-L: WAIT 1i8
    WAIT 1
ENDIF

// CHECK-NEXT-L: MAIN_1:
// CHECK-NEXT-L: ANDOR 2i8
// CHECK-NEXT-L: IS_THING_EQUAL_TO_THING &8 1i8
// CHECK-NEXT-L: IS_THING_EQUAL_TO_THING &8 2i8
// CHECK-NEXT-L: IS_THING_EQUAL_TO_THING &8 3i8
// CHECK-NEXT-L: GOTO_IF_FALSE @MAIN_2
IF  x = 1
AND x = 2
AND x = 3
    // CHECK-NEXT-L: WAIT 3i8
    WAIT 3
ENDIF

// CHECK-NEXT-L: MAIN_2:
// CHECK-NEXT-L: ANDOR 22i8
// CHECK-NEXT-L: IS_THING_EQUAL_TO_THING &8 1i8
// CHECK-NEXT-L: IS_THING_EQUAL_TO_THING &8 2i8
// CHECK-NEXT-L: IS_THING_EQUAL_TO_THING &8 3i8
// CHECK-NEXT-L: GOTO_IF_FALSE @MAIN_3
IF x = 1
OR x = 2
OR x = 3
    // CHECK-NEXT-L: WAIT 2i8
    WAIT 2
ENDIF

// CHECK-NEXT-L: MAIN_3:
// CHECK-L:      IS_THING_EQUAL_TO_THING &8 1i8
// CHECK-NEXT-L: NOT IS_THING_EQUAL_TO_THING &8 2i8
IF x = 1
OR NOT x = 2
    WAIT 0
ENDIF

TERMINATE_THIS_SCRIPT