// RUN: %gta3sc %s --config=gtavc -emit-ir2 -o - | %FileCheck %s

VAR_INT x

// CHECK-NEXT-L: ANDOR 0i8
// CHECK-NEXT-L: IS_INT_VAR_EQUAL_TO_NUMBER &8 0i8
// CHECK-NEXT-L: GOTO_IF_FALSE @MAIN_1
IF x = 0
    // CHECK-NEXT-L: WAIT 1i8
    WAIT 1
ENDIF

// CHECK-NEXT-L: MAIN_1:
// CHECK-NEXT-L: ANDOR 0i8
// CHECK-NEXT-L: IS_INT_VAR_EQUAL_TO_NUMBER &8 0i8
// CHECK-NEXT-L: GOTO_IF_FALSE @MAIN_2
IF x = 0
    // CHECK-NEXT-L: WAIT 2i8
    // CHECK-NEXT-L: GOTO @MAIN_3
    WAIT 2
ELSE
    // CHECK-NEXT-L: MAIN_2:
    // CHECK-NEXT-L: WAIT 3i8
    WAIT 3
ENDIF

// CHECK-NEXT-L: MAIN_3:
// CHECK-NEXT-L: ANDOR 0i8
// CHECK-NEXT-L: IS_INT_VAR_EQUAL_TO_NUMBER &8 0i8
// CHECK-NEXT-L: GOTO_IF_FALSE @MAIN_4
WHILE x = 0
    // CHECK-NEXT-L: WAIT 10i8
    // CHECK-NEXT-L: GOTO @MAIN_3
    WAIT 10
ENDWHILE

// CHECK-NEXT-L: MAIN_4:
// CHECK-NEXT-L: SET_VAR_INT &8 0i8
REPEAT 10 x
    // CHECK-NEXT-L: MAIN_5:
    // CHECK-NEXT-L: WAIT 11i8
    WAIT 11
    // CHECK-NEXT-L: ADD_VAL_TO_INT_VAR &8 1i8
    // CHECK-NEXT-L: IS_INT_VAR_GREATER_OR_EQUAL_TO_NUMBER &8 10i8
    // CHECK-NEXT-L: GOTO_IF_FALSE @MAIN_5
ENDREPEAT

// CHECK-NEXT-L: TERMINATE_THIS_SCRIPT
TERMINATE_THIS_SCRIPT