// RUN: %gta3sc %s --config=gtasa --guesser -emit-ir2 -o - | %FileCheck %s

// CHECK-L: SET_TOTAL_NUMBER_OF_MISSIONS 3i8
SET_TOTAL_NUMBER_OF_MISSIONS 0
// CHECK-L: SET_PROGRESS_TOTAL 17i8
SET_PROGRESS_TOTAL 0

GOSUB prog10
LOAD_AND_LAUNCH_MISSION prog2.sc
LOAD_AND_LAUNCH_MISSION prog5.sc

TERMINATE_THIS_SCRIPT

prog10:
PLAYER_MADE_PROGRESS 10
REGISTER_MISSION_PASSED prog10
RETURN

