// RUN: %gta3sc %s --config=gtasa --guesser -emit-ir2 -o - | %FileCheck %s

// CHECK-L: SKIP_CUTSCENE_START_INTERNAL @MAIN_1
SKIP_CUTSCENE_START
// CHECK-NEXT-L: WAIT 2i8
// CHECK-NEXT-L: WAIT 3i8
WAIT 2
WAIT 3
// CHECK-NEXT-L: MAIN_1:
// CHECK-NEXT-L: SKIP_CUTSCENE_END
SKIP_CUTSCENE_END

// CHECK-NEXT-L: TERMINATE_THIS_SCRIPT
TERMINATE_THIS_SCRIPT
