// # Check IR2
// RUN: %gta3sc %s --config=gtasa --guesser -emit-ir2 | %FileCheck %s
//
// # Check SCM Header and IMG Building
// RUN: mkdir "%/T/streaming" || echo _
// RUN: %gta3sc %s --config=gtasa --guesser -o "%/T/streaming/main.scm"
// RUN: %checksum "%T/streaming/main.scm" 45ef8fb66c91271cb7b82c3946bc6eb2
// RUN: %checksum "%T/streaming/script.img" d7168d3a64517c11ac12b963ec020681
//

VAR_INT n

// Add a mission blocks to ensure missions do not break streaming blocks.
LOAD_AND_LAUNCH_MISSION mission1.sc

{
    // CHECK-L:      REGISTER_STREAMED_SCRIPT_INTERNAL 0i8
    // CHECK-NEXT-L: REGISTER_STREAMED_SCRIPT_INTERNAL 1i8
    // CHECK-NEXT-L: REGISTER_STREAMED_SCRIPT_INTERNAL 2i8
    // CHECK-NEXT-L: REGISTER_STREAMED_SCRIPT_INTERNAL 3i8
    // CHECK-NEXT-L: REGISTER_STREAMED_SCRIPT_INTERNAL 4i8
    REGISTER_STREAMED_SCRIPT stream1.sc
    REGISTER_STREAMED_SCRIPT attractor1.sc
    REGISTER_STREAMED_SCRIPT brain1.sc
    REGISTER_STREAMED_SCRIPT object1.sc
    REGISTER_STREAMED_SCRIPT ped1.sc

    // CHECK-NEXT-L: REGISTER_ATTRACTOR_SCRIPT_BRAIN_FOR_CODE_USE 1i8 'DANCER'
    REGISTER_ATTRACTOR_SCRIPT_BRAIN_FOR_CODE_USE attractor1.sc DANCER

    // CHECK-NEXT-L: REGISTER_SCRIPT_BRAIN_FOR_CODE_USE 2i8 'HOUSE'
    REGISTER_SCRIPT_BRAIN_FOR_CODE_USE brain1.sc HOUSE

    // CHECK-NEXT-L: ALLOCATE_STREAMED_SCRIPT_TO_OBJECT 3i8 -1i8 100i8 6.0f 1i8
    ALLOCATE_STREAMED_SCRIPT_TO_OBJECT object1.sc KB_BANDIT_U 100 6.0 1

    // CHECK-NEXT-L: ALLOCATE_STREAMED_SCRIPT_TO_RANDOM_PED 4i8 28i8 100i8
    ALLOCATE_STREAMED_SCRIPT_TO_RANDOM_PED ped1.sc BMYDRUG 100

    // CHECK-NEXT-L: STREAM_SCRIPT 0i8
    STREAM_SCRIPT stream1.sc

    // CHECK-L: NOT HAS_STREAMED_SCRIPT_LOADED 0i8
    WHILE NOT HAS_STREAMED_SCRIPT_LOADED stream1.sc
        WAIT 0
    ENDWHILE

    // CHECK-L: START_NEW_STREAMED_SCRIPT 0i8
    START_NEW_STREAMED_SCRIPT stream1.sc

    // CHECK-NEXT-L: MARK_STREAMED_SCRIPT_AS_NO_LONGER_NEEDED 0i8
    MARK_STREAMED_SCRIPT_AS_NO_LONGER_NEEDED stream1.sc

    // CHECK-NEXT-L: GET_NUMBER_OF_INSTANCES_OF_STREAMED_SCRIPT 0i8 &8
    GET_NUMBER_OF_INSTANCES_OF_STREAMED_SCRIPT stream1.sc n
    WHILE n > 0
        // CHECK-L: GET_NUMBER_OF_INSTANCES_OF_STREAMED_SCRIPT 0i8 &8
        GET_NUMBER_OF_INSTANCES_OF_STREAMED_SCRIPT stream1.sc n
    ENDWHILE

    // CHECK-L: REMOVE_STREAMED_SCRIPT 0i8
    REMOVE_STREAMED_SCRIPT stream1.sc

    // CHECK-L: SWITCH_OBJECT_BRAINS 0i8 1i8
    SWITCH_OBJECT_BRAINS stream1.sc TRUE
}

// Add another mission block, this time after all streamed declarations happened.
WAIT 100
LOAD_AND_LAUNCH_MISSION mission2.sc

// CHECK-L: TERMINATE_THIS_SCRIPT
TERMINATE_THIS_SCRIPT

// mission1.sc
// CHECK-NEXT-L: #MISSION_BLOCK_START 0
// CHECK-NEXT-L: PRINT_HELP 'MISS1'
// CHECK-NEXT-L: TERMINATE_THIS_SCRIPT
// CHECK-NEXT-L: #MISSION_BLOCK_END

// mission2.sc
// CHECK-NEXT-L: #MISSION_BLOCK_START 1
// CHECK-NEXT-L: PRINT_HELP 'MISS2'
// CHECK-NEXT-L: TERMINATE_THIS_SCRIPT
// CHECK-NEXT-L: #MISSION_BLOCK_END

// stream1.sc
// CHECK-NEXT-L: #STREAMED_BLOCK_START 0
// CHECK-NEXT-L: PRINT_HELP 'STREAM1'
// CHECK-NEXT-L: TERMINATE_THIS_SCRIPT
// CHECK-NEXT-L: #STREAMED_BLOCK_END

// attractor1.sc
// CHECK-NEXT-L: #STREAMED_BLOCK_START 1
// CHECK-NEXT-L: PRINT_HELP 'ATTR1'
// CHECK-NEXT-L: TERMINATE_THIS_SCRIPT
// CHECK-NEXT-L: #STREAMED_BLOCK_END

// brain1.sc
// CHECK-NEXT-L: #STREAMED_BLOCK_START 2
// CHECK-NEXT-L: PRINT_HELP 'BRAIN1'
// CHECK-NEXT-L: TERMINATE_THIS_SCRIPT
// CHECK-NEXT-L: #STREAMED_BLOCK_END

// object1.sc
// CHECK-NEXT-L: #STREAMED_BLOCK_START 3
// CHECK-NEXT-L: PRINT_HELP 'OBJ1'
// CHECK-NEXT-L: TERMINATE_THIS_SCRIPT
// CHECK-NEXT-L: #STREAMED_BLOCK_END

// ped1.sc
// CHECK-NEXT-L: #STREAMED_BLOCK_START 4
// CHECK-NEXT-L: PRINT_HELP 'PED1'
// CHECK-NEXT-L: TERMINATE_THIS_SCRIPT
// CHECK-NEXT-L: #STREAMED_BLOCK_END
