/** \file
 *  This C header file was generated by $ANTLR version 3.5.2
 *
 *     -  From the grammar source file : gta3script.g
 *     -                            On : 2016-02-16 22:56:15
 *     -                 for the lexer : gta3scriptLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer 
gta3scriptLexer

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pgta3scriptLexer, which is returned from a call to gta3scriptLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 *
 * The methods in pgta3scriptLexer are  as follows:
 *
 *  - 
 void
      pgta3scriptLexer->T__78(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__79(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__80(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__81(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__82(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__83(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__84(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__85(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__86(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__87(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__88(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__89(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__90(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__91(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__92(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__93(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__94(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__95(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__96(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__97(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__98(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__99(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__100(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__101(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__102(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__103(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__104(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__105(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__106(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__107(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__108(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__109(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__110(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__111(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__112(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__113(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__114(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__115(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T__116(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->NOT(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->AND(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->OR(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->IF(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->ELSE(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->ENDIF(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->WHILE(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->ENDWHILE(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->REPEAT(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->ENDREPEAT(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->SWITCH(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->ENDSWITCH(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->CASE(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->DEFAULT(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->BREAK(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->CONTINUE(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->VAR_INT(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->LVAR_INT(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->VAR_FLOAT(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->LVAR_FLOAT(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->VAR_TEXT_LABEL(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->LVAR_TEXT_LABEL(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->VAR_TEXT_LABEL16(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->LVAR_TEXT_LABEL16(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->IDENTIFIER(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->INTEGER(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->FLOAT(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->LONG_STRING(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->SHORT_STRING(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->COMMENT(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->WS(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->HEX_LITERAL(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->OCT_LITERAL(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->DEC_LITERAL(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->FLOAT_LITERAL(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->EXPONENT(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->DEC_DIGIT(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->HEX_DIGIT(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->OCT_DIGIT(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->ESC_SEQ(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->OCTAL_ESC(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->UNICODE_ESC(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->A(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->B(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->C(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->D(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->E(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->F(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->G(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->H(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->I(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->J(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->K(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->L(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->M(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->N(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->O(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->P(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->Q(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->R(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->S(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->T(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->U(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->V(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->W(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->X(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->Y(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->Z(pgta3scriptLexer)
 *  - 
 void
      pgta3scriptLexer->Tokens(pgta3scriptLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_gta3scriptLexer_H
#define _gta3scriptLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct gta3scriptLexer_Ctx_struct gta3scriptLexer, * pgta3scriptLexer;



   #define _empty NULL


#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for 
gta3scriptLexer

 */
struct gta3scriptLexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;

     void
     (*mT__78)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__79)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__80)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__81)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__82)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__83)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__84)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__85)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__86)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__87)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__88)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__89)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__90)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__91)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__92)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__93)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__94)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__95)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__96)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__97)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__98)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__99)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__100)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__101)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__102)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__103)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__104)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__105)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__106)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__107)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__108)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__109)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__110)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__111)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__112)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__113)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__114)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__115)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT__116)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mNOT)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mAND)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mOR)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mIF)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mELSE)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mENDIF)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mWHILE)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mENDWHILE)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mREPEAT)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mENDREPEAT)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mSWITCH)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mENDSWITCH)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mCASE)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mDEFAULT)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mBREAK)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mCONTINUE)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mVAR_INT)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mLVAR_INT)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mVAR_FLOAT)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mLVAR_FLOAT)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mVAR_TEXT_LABEL)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mLVAR_TEXT_LABEL)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mVAR_TEXT_LABEL16)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mLVAR_TEXT_LABEL16)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mIDENTIFIER)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mINTEGER)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mFLOAT)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mLONG_STRING)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mSHORT_STRING)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mCOMMENT)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mWS)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mHEX_LITERAL)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mOCT_LITERAL)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mDEC_LITERAL)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mFLOAT_LITERAL)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mEXPONENT)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mDEC_DIGIT)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mHEX_DIGIT)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mOCT_DIGIT)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mESC_SEQ)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mOCTAL_ESC)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mUNICODE_ESC)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mA)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mB)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mC)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mD)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mE)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mF)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mG)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mH)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mI)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mJ)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mK)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mL)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mM)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mN)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mO)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mP)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mQ)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mR)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mS)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mT)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mU)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mV)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mW)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mX)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mY)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mZ)	(struct gta3scriptLexer_Ctx_struct * ctx);

     void
     (*mTokens)	(struct gta3scriptLexer_Ctx_struct * ctx);
    const char * (*getGrammarFileName)();
    void            (*reset)  (struct gta3scriptLexer_Ctx_struct * ctx);
    void	    (*free)   (struct gta3scriptLexer_Ctx_struct * ctx);
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pgta3scriptLexer gta3scriptLexerNew         (
pANTLR3_INPUT_STREAM
 instream);
ANTLR3_API pgta3scriptLexer gta3scriptLexerNewSSD      (
pANTLR3_INPUT_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
lexer
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define T__78      78
#define T__79      79
#define T__80      80
#define T__81      81
#define T__82      82
#define T__83      83
#define T__84      84
#define T__85      85
#define T__86      86
#define T__87      87
#define T__88      88
#define T__89      89
#define T__90      90
#define T__91      91
#define T__92      92
#define T__93      93
#define T__94      94
#define T__95      95
#define T__96      96
#define T__97      97
#define T__98      98
#define T__99      99
#define T__100      100
#define T__101      101
#define T__102      102
#define T__103      103
#define T__104      104
#define T__105      105
#define T__106      106
#define T__107      107
#define T__108      108
#define T__109      109
#define T__110      110
#define T__111      111
#define T__112      112
#define T__113      113
#define T__114      114
#define T__115      115
#define T__116      116
#define A      4
#define AND      5
#define ARGS      6
#define ARRAY      7
#define B      8
#define BLOCK      9
#define BREAK      10
#define C      11
#define CASE      12
#define COMMAND      13
#define COMMENT      14
#define CONTINUE      15
#define D      16
#define DEC_DIGIT      17
#define DEC_LITERAL      18
#define DEFAULT      19
#define E      20
#define ELSE      21
#define ENDIF      22
#define ENDREPEAT      23
#define ENDSWITCH      24
#define ENDWHILE      25
#define ESC_SEQ      26
#define EXPONENT      27
#define F      28
#define FLOAT      29
#define FLOAT_LITERAL      30
#define G      31
#define H      32
#define HEX_DIGIT      33
#define HEX_LITERAL      34
#define I      35
#define IDENTIFIER      36
#define IF      37
#define INTEGER      38
#define J      39
#define K      40
#define L      41
#define LABEL      42
#define LONG_STRING      43
#define LVAR_FLOAT      44
#define LVAR_INT      45
#define LVAR_TEXT_LABEL      46
#define LVAR_TEXT_LABEL16      47
#define M      48
#define N      49
#define NOT      50
#define O      51
#define OCTAL_ESC      52
#define OCT_DIGIT      53
#define OCT_LITERAL      54
#define OR      55
#define P      56
#define Q      57
#define R      58
#define REPEAT      59
#define S      60
#define SCOPE      61
#define SHORT_STRING      62
#define SWITCH      63
#define T      64
#define U      65
#define UNICODE_ESC      66
#define V      67
#define VAR_FLOAT      68
#define VAR_INT      69
#define VAR_TEXT_LABEL      70
#define VAR_TEXT_LABEL16      71
#define W      72
#define WHILE      73
#define WS      74
#define X      75
#define Y      76
#define Z      77
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for gta3scriptLexer
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
