// RUN: %gta3sc %s -O -fcleo --config=gtasa --guesser -emit-ir2 -o - | %FileCheck %s

// CHECK-L: NOP
NOP

// CHECK-NEXT-L: GOSUB @MAIN_1
// CHECK-NEXT-L: GOSUB @MAIN_2
// CHECK-NEXT-L: CLEO_CALL @MAIN_3 0i8
// CHECK-NEXT-L: TERMINATE_THIS_SCRIPT
GOSUB gosub1
GOSUB gosub2
CLEO_CALL func1 0
TERMINATE_THIS_SCRIPT

// Dead after TERMINATE_THIS_SCRIPT
// CHECK-NOT-L: PRINT_HELP 'DEAD11'
// CHECK-NOT-L: PRINT_HELP 'DEAD12'
// CHECK-NOT-L: PRINT_HELP 'DEAD13'
PRINT_HELP DEAD11
PRINT_HELP DEAD12
PRINT_HELP DEAD13

// CHECK-L: MAIN_1:
// CHECK-NEXT-L: WAIT 100i8
// CHECK-NEXT-L: GOTO @MAIN_2
gosub1:
WAIT 100
GOTO gosub2

// Dead after GOTO
// CHECK-NOT-L: PRINT_HELP 'DEAD21'
// CHECK-NOT-L: PRINT_HELP 'DEAD22'
// CHECK-NOT-L: PRINT_HELP 'DEAD23'
PRINT_HELP DEAD21
PRINT_HELP DEAD22
PRINT_HELP DEAD23

// CHECK-L: MAIN_2:
// CHECK-NEXT-L: WAIT 200i16
// CHECK-NEXT-L: RETURN
gosub2:
WAIT 200
RETURN

// Dead after RETURN
// CHECK-NOT-L: PRINT_HELP 'DEAD31'
// CHECK-NOT-L: PRINT_HELP 'DEAD32'
// CHECK-NOT-L: PRINT_HELP 'DEAD33'
PRINT_HELP DEAD31
PRINT_HELP DEAD32
PRINT_HELP DEAD33

// never referenced, but still, it's a label, we should respect it.
// CHECK-L: PRINT_HELP 'NOTDEAD'
// CHECK-NEXT-L: RETURN
not_dead_code:
PRINT_HELP NOTDEAD
RETURN

// CHECK-NEXT-L: MAIN_3:
// CHECK-NEXT-L: CLEO_RETURN 0i8
{
func1:
CLEO_RETURN 0
}

// Dead after CLEO_RETURN
// CHECK-NOT-L: PRINT_HELP 'DEAD41'
// CHECK-NOT-L: PRINT_HELP 'DEAD42'
// CHECK-NOT-L: PRINT_HELP 'DEAD43'
PRINT_HELP DEAD41
PRINT_HELP DEAD42
PRINT_HELP DEAD43

// Not dead because it's over a unreferenced label.
// CHECK-L: NOP
not_dead_again:
DUMP
  00 00
ENDDUMP

// Unreferenced but not dead as well.
// CHECK-NEXT-L: WAIT 400i16
// CHECK-NEXT-L: RETURN
gosub4:
WAIT 400
RETURN

// Dead because after a RETURN and no label over this.
// CHECK-NOT-L: NOP
DUMP
  00 00
ENDDUMP
